steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','movies-telegram-bot-test','--target','test','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run','--rm','movies-telegram-bot-test','npm','test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/release:$COMMIT_SHA','--target','release','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/release:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'telegram-bot'
  - '--image'
  - 'gcr.io/$PROJECT_ID/release:$COMMIT_SHA'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'  